export const PROFILES_LIST = "PROFILES_LIST";
export const PROFILE_CREATE = "PROFILE_CREATE";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_DELETE = "PROFILE_DELETE";
export const PROFILE_DETAIL = "PROFILE_DETAIL";
